### ISSUE TITLE
Strength of Mount Mugamba Issue

### ISSUE THREAD

**Issue by Orcci** [LightsHope/server#1105]
Hello,

I'm playing on Lightbringer patch 1.8 and i have an issue with Zandalar Tribe reputation neck "Strength of Mount Mugamba". Yesterday i was in ZG and got revered reputation with ZT and today when walking to ZT island to change my "Strength of Mugamba" honored version to revered version it wont let me do it. Attached screenshot will show you all.

Br,
Orcci
![problem zg quest](https://user-images.githubusercontent.com/34944710/34442674-5e304214-eccc-11e7-92a9-17e15c5dd1e1.jpg)

**Comment by Questida** [comment]
suggest deleting the WDB folder in the WoW folder while fully exited from the game.

**Comment by Orcci** [comment]
Done that, also turned off all the addons as GM suggested ingame. Nothing seems to help.

**Comment by Questida** [comment]
Looking carefully at your image, you seem have the Strength of Mugamba item id= 19575 in your backpack. You are being offered the wrong quest id=8042, rather than id=8043. 

If you have cleared your WDB folder while fully exited, this is a quest chain problem that the GMs could check for you OR it may be a database bug. which would affect all.

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you
