### ISSUE TITLE
Captain Sander's Treasure Map bugged for Horde

### ISSUE THREAD

**Issue by jiegema** [LightsHope/server#248]
Elysium server, current patch

Captain Sander's Treasure Map does not start the quest Captain Sander's Hidden Treasure for HORDE

HORDE should be able to use this the mentioned item appropriately and be able to complete this quest.

It is evident in multiple past responses on the aowow database that the item was obtainable and the quest completeable by Horde.  This server does not seem to be working as was initially intended.

**Comment by GuybrushGit** [comment]
Fixed on https://github.com/LightsHope/server/pull/37

**Comment by jiegema** [comment]
I will try to delete WDB/WTF folders (although I did that before logging on to this server).  I will follow-up with an update.

**Comment by jiegema** [comment]
Deleting WDB/WTF folders did not fix the issue.  Still prompted with "That quest is not available to your race."

**Comment by GuybrushGit** [comment]
The fix is not live yet.

**Comment by jiegema** [comment]
Still does not work.  The quest can now be accepted but the objects cannot be interacted with as horde.  I will put in a new issue.
