### ISSUE TITLE
Fahrad does not offer Quest: Junkboxes Needed 

### ISSUE THREAD

**Issue by Nelythia** [LightsHope/server#357]
The quest Junkboxes Needed http://wowwiki.wikia.com/wiki/Quest:Junkboxes_Needed & http://www.wowhead.com/quest=8249/junkboxes-needed does not seem to be ingame yet.

It is possible that this quest got introduced at a later patch, 1.11/1.12 however I am not sure if the developers are aware of it.

I am reporting this as a bug nevertheless, as I hope you are aware of this quest being introduced in vanilla at some point but I do not have any confirmation that you are.

My plan was to do the WotLK Feats of Strength "Insane in the Membrane" during vanilla, as I like the challenge and there is not much to do for me ingame currently.

Noticed on Darrowshire, patch 1.8.

**Guybrush comment from Elysium Github**

> Quest got introduced with patch 1.7.

**Comment by GuybrushGit** [comment]
Have you tested this at all? Or just copy pasted?

It should be fixed already.

**Comment by Nelythia** [comment]
I have not seen any fix for that on Github, I just checked too and he is still not offering it on Darrowshire.

**Comment by GuybrushGit** [comment]
Quest works in dev but it has a level 50 and 3000 Ravenholdt rep requirement, do you have both of these?

**Comment by Nelythia** [comment]
I am level 60 and you can not get any reputation with Ravenholdt except by doing this quest.
The only other way is to kill syndicate mobs until 11999/12000 but that kill reputation is only added with TBC, thus the rep requirement should be neutral as it was in retail as well.

I checked both links provided in OP and can not find that the quest has a requirement of friendly reputation, especially when you can not even get that in vanilla except by these turn ins.

**Comment by GuybrushGit** [comment]
Vanilla wowwiki shows something else: http://wowwiki.wikia.com/wiki/Ravenholdt?oldid=324150

**Comment by Cabro** [comment]
I think there is a mistake that the quest requires FRIENDLY, because this comment denies that: http://www.wowhead.com/quest=8249/junkboxes-needed#comments:id=111075:reply=11350
